# Jupyter Book 配置
# 保存为: _config.yml

title: "MOF 学习手册"
author: "Your Name"
logo: ""  # 可以填 logo 路径，比如: images/logo.png
language: zh
execute:
  execute_notebooks: auto  # "off" "auto" "force"
  timeout: 60

html:
  favicon: ""
  use_issues_button: false
  use_repository_button: false

sphinx:
  config:
    myst_enable_extensions:
      - colon_fence        # ::: 语法
      - dollarmath         # $...$ 行内公式
      - amsmath            # 多行公式
      - deflist            # 定义列表
      - html_admonition
      - html_image
      - linkify
      - substitution
      - tasklist